### PR TITLE
ML-Build: Manually install Bazel version compatible with the current Tensorflow release 1.13.0

### PR DESCRIPTION
**Pull request by rajat2004**
Initial fix for #32

### CODE REVIEW

**Comment by rajat2004** [comment]
Well, at least it's not complaining about Bazel anymore
@rsnk96 Can you have a look at the support options which it's asking for?

**Comment by rsnk96** [comment]
For future reference, the configration flags can be found in [`configure.py`](https://github.com/tensorflow/tensorflow/blob/r2.0/configure.py) in the TF repo

**Comment by rsnk96** [comment]
Good work @rajat2004

**Comment by rajat2004** [comment]
Thanks a lot @rsnk96 for this and granting push access.
I'll keep this in mind about putting the commands for installing the latest version in comments

**Pull request merged**
