### PR TITLE
Detect CUDA install and configure OpenCV accordingly

### PR DESCRIPTION
**Pull request by rajat2004**

### CODE REVIEW

**Comment by rajat2004** [comment]
There is a way to find the Compute Capability, not exactly a command-line option, need to compile the following and run
```
#include <stdio.h>
#include "cuda.h"
int main() {
    cudaDeviceProp prop;
    cudaGetDeviceProperties(&prop, 0);
    printf("%d", prop.major * 10 + prop.minor);
}
```
But this won't work inside Docker I think while building, since there's no device yet
Could add something like pass an env variable to the script, to automate this

**Comment by rsnk96** [comment]
LGTM, would be nice to compile for the required Compute Capability only.

Also just need to verify if having comments in between the CMake command causes errors, I remember it did in the older versions of cmake. Doesn't seem to be causing an error in travis, will test on a system shortly and get back.

**Comment by rajat2004** [comment]
The comments are after the `cmake` command has ended, will be obvious to someone who's changing the scripts by hand
The code for checking the CC could be added as a file in the `extras` folder, but suppose when building a docker image, the device won't be present which would cause a problem
A workaround could be that an env variable `CUDA_ARCH_BIN` or something could be passed to the script, if it's set, use that else we build for all supported CC >= 5.3

**Comment by rajat2004** [comment]
Updated the flags to build for all supported architectures by default
Some customization could be done, such as -
* Check if `nvidia-smi` is working, then maybe compile the above CUDA code and build for the specific arch
* User passes an env variable to build for a specific arch

**Comment by rsnk96** [comment]
Will leave those as upgrades to be made in the future

**Review by rsnk96 — APPROVED** [review]

**Comment by rajat2004** [comment]
Thanks for the review! Merged

**Pull request merged**
