### PR TITLE
OpenCV Improvements & Fixes Part 2

### PR DESCRIPTION
**Pull request by rajat2004**
1. Build OpenCV with GStreamer
2. Small cleanups and fixes in FFmpeg shared library config
3. Fix CMake not finding Python library
4. Travis cleanups and updates - Not related to OpenCV
5. Enable non-free algos such as SIFT, SURF

Issue - https://github.com/rsnk96/Ubuntu-Setup-Scripts/issues/20

### CODE REVIEW

**Comment by rajat2004** [comment]
@rsnk96 Any idea why Anaconda is present in the PATH?
This is the output in Travis - 
`
/home/travis/virtualenv/python3.7.5/bin:/opt/anaconda3/envs/py27/bin:/opt/anaconda3/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v12.13.1/bin:/home/travis/.rvm/gems/ruby-2.6.5/bin:/home/travis/.rvm/gems/ruby-2.6.5@global/bin:/home/travis/.rvm/rubies/ruby-2.6.5/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin
`

Other things look okay-
py3Ex - `/home/travis/virtualenv/python3.7.5/bin/python3`
py3In -  `/opt/python/3.7.5/include/python3.7m`
py3Pack - `/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages`

**Comment by rsnk96** [comment]
Can't think of a reason

**Comment by rajat2004** [comment]
Hmm, I'm not seeing this problem when testing on a separate branch with the current branch as the base

PATH - `/home/travis/virtualenv/python3.7.1/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin`

Branch - https://github.com/rajat2004/Ubuntu-Setup-Scripts/tree/opencv-fixes-test
Travis build - https://travis-ci.com/rajat2004/Ubuntu-Setup-Scripts/builds/142307722

Let's see...

**Comment by rajat2004** [comment]
@rsnk96 Got it! It was in the most obvious place which I had completely neglected to look at.
The paths have been modified in the `Settings` for the repo in Travis, can be seen by going to `More Options` on the upper right side in Travis.
Link to the settings - https://travis-ci.org/rsnk96/Ubuntu-Setup-Scripts/settings
I think this is also the reason why problems with paths such as in https://github.com/rsnk96/Ubuntu-Setup-Scripts/issues/52 were never reproducible in Travis

I'll drop the commits for testing of the paths, probably the changes to the paths in the settings are not needed since they have not been made in my own repo, and the builds are passing, but will look into this more deeply first

**Comment by rajat2004** [comment]
The last commit is something which I feel is good to have but can be removed. Any thoughts?

**Review by rsnk96 — APPROVED** [review]

**Comment by rsnk96** [comment]
Good find on Travis's path!

**Comment by rajat2004** [comment]
@rsnk96 Thanks! I think it should be okay to remove the path modifications, but would like to confirm that. This PR also seems to be good to go
Will probably follow up with an update to the Readme regarding some of the newer changes, after this and the other Tensorflow PR has been merged

**Comment by rajat2004** [comment]
The current PATH settings in Travis - 
PATH:   `/opt/anaconda3/envs/py27/bin:/opt/anaconda3/bin:$PATH`
LD_LIBRARY_PATH:   `$LD_LIBRARY_PATH:/opt/ffmpeg-build-script/workspace/lib`
PKG_CONFIG_LIBDR:  `$PKG_CONFIG_LIBDIR:/opt/ffmpeg-build-script/workspace/lib/`
PKG_CONFIG_PATH:   `$(pkg-config --variable pc_path pkg-config)${PKG_CONFIG_PATH:+:}/opt/ffmpeg-build-script/workspace/lib/pkgconfig`
I'll start removing and modifictions and see the result

**Comment by rajat2004** [comment]
Removed all the modifications and Travis build is passing, everything looks okay

**Pull request merged**
