### PR TITLE
Add nvidia-docker2 installation

### PR DESCRIPTION
**Pull request by rajat2004**
It has been commented out since this should be installed only if an Nvidia GPU is present
Things to note-

1. `nvidia-docker` should be uninstalled before installing `nvidia-docker2`. This can be added.
2. We can check for the presence of the GPU using `nvidia-smi` and then only install

Source - https://github.com/NVIDIA/nvidia-docker#quickstart

### CODE REVIEW

**Comment by rajat2004** [comment]
#14 can be closed after this goes in
Should we have `nvidia-docker` installation also?

**Review by rsnk96 — CHANGES_REQUESTED** [review]
For the removal of `nvidia-docker`, why not do it as suggested in the link you put in the comments
```python
# If you have nvidia-docker 1.0 installed: we need to remove it and all existing GPU containers
docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
sudo apt-get purge -y nvidia-docker
```

And let's add the `nvidia-smi` part and make it uncommented by default. Can be done similar to [this](https://github.com/rsnk96/Ubuntu-Setup-Scripts/blob/740abc319f5b01dab7c91f705291bfb40d515105/ML-Basic.sh#L37) part of the other scripts

**Comment by rajat2004** [comment]
@rsnk96 Changes made

**Review by rsnk96 — APPROVED** [review]
Looks great!

**Comment by rajat2004** [comment]
Added missing -y flag, good to go now

**Pull request merged**
