### PR TITLE
ML-Build Fixes

### PR DESCRIPTION
**Pull request by rajat2004**
Use default Tensorflow version configuration (Version 2 by default)
Install latest supported Bazel version for the Tensorflow version being installed

### CODE REVIEW

**Comment by rajat2004** [comment]
Removed `NVCUVID` from the Readme since there were problems while compiling with it enabled, also googling it shows that it's deprecated, isn't supported in later CUDA versions (>8.0 it seems). Not completely sure, therefore just removing from Readme

**Comment by rsnk96** [comment]
Looks like you're in a mood to fix a lot of bugs :)

**Review by rsnk96 — APPROVED** [review]
Looks like NVCUVID is disabled forcefully in OpenCV's `CMakeLists.txt` [directly](https://github.com/opencv/opencv/blob/7b12cbd7dcbb025c31e7630c9ae709493a8f3d62/CMakeLists.txt#L248) even if you choose to enable it in your build configuration

**Comment by rajat2004** [comment]
> Looks like you're in a mood to fix a lot of bugs :)

Pretty bored right now of series, books, etc., so scrolling through Travis build logs :-)

Thanks for merging!
Hadn't looked at OpenCV's CMakeList, though had this problem sometime back and had forgotten to make the change. It was with 3.4.5 though

**Pull request merged**
