### PR TITLE
OpenCV Installation improvements & fixes

### PR DESCRIPTION
**Pull request by rajat2004**
One of the fixes from the dicussion in https://github.com/rsnk96/Ubuntu-Setup-Scripts/issues/52

### CODE REVIEW

**Comment by rajat2004** [comment]
Travis is passing the opencv builds, but I think it'll be good to do a double check in a Docker container

**Review by rsnk96 — APPROVED** [review]

**Comment by rajat2004** [comment]
@rsnk96 By any chance, were you able to test these changes in a docker container?
I think both these changes should be good to go, but just confirming

**Comment by rsnk96** [comment]
Tested once, didn't work out of the box, primarily because `run_and_echo()` reloads the environment within the bash script effectively, but doesn't update the environment which started the script in the first place (i.e. the shell process). Easy way around this is to just start a new sub-process with the updated `SHELLRC` file like [here](https://github.com/rsnk96/Ubuntu-Setup-Scripts/blob/9c7547ada90e8d6e973180a17760f67b4f21fb51/1-BasicSetUp.sh#L184) just before the script exits (and this has to be done within an `if [[ ! -n $CIINSTALL ]]; then....fi` so that Travis doesn't fail with this addition)

Also need to check if OpenCV built with the updated version of FFmpeg, will post an update on that in a while

**Comment by rajat2004** [comment]
@rsnk96 Ohk, thanks for the detailed explanation and testing, otherwise wouldn't have caught the problem. Would have tested it myself but don't have a very good internet connection right now.
I've Pushed a fix as you described

**Comment by rajat2004** [comment]
Things are definitely wrong right now - 
```
./opencvDirectInstall.sh: line 30: export: `--variable': not a valid identifier
./opencvDirectInstall.sh: line 30: export: `pkg-config)': not a valid identifier
```
https://travis-ci.org/rsnk96/Ubuntu-Setup-Scripts/jobs/626129056#L1195
Need to look into this and fix it

**Comment by rajat2004** [comment]
Error's not there now, changed `run_and_echo () {  $1 ... }` to `run_and_echo () {  eval $1 ... }` to force it to run the embedded commands

**Comment by rajat2004** [comment]
Lapacke change fixes the Atlas not found problem, the OpenBLAS ones generally need code change
Will try to have a go at some of the other errors in https://github.com/rsnk96/Ubuntu-Setup-Scripts/issues/20

**Comment by rsnk96** [comment]
Updates looks good, and haha didn't know that there was a version of `lapack` with an `e` that has more features. Whenever you feel you've hit a wall wrt fixing the issues in https://github.com/rsnk96/Ubuntu-Setup-Scripts/issues/20, feel free to merge this PR

**Comment by rajat2004** [comment]
@rsnk96 Fixing the other errors will need more time, will try to do that in another PR, this one has enough things in it already
It'll be good to have another test in a docker container soon, but will merge this for now. Also will update the issue with the current errors

**Pull request merged**
