### PR TITLE
GenSoftware: Change conda install to pip

### PR DESCRIPTION
**Pull request by rajat2004**
`conda install` failing for some reason. Trying out `pip` in place of that. Also makes it consistent with the installation in the previous line

### CODE REVIEW

**Comment by rajat2004** [comment]
The Travis build is now atleast running both the scripts entirely. But I'm not sure why it's saying the build failed.
Maybe it doesn't like the `zsh` installation @rsnk96 ?

**Comment by rajat2004** [comment]
The problem seems to be with the `pip` install itself but no idea why since it didn't have problem with the previous `pip` install line
Or is it with the next line `sed -i.bak "/anaconda3/d" ~/.zshrc`

**Comment by rsnk96** [comment]
This is likely because `msgpack` takes time to build from `pip`, and Travis times out the operation. It happens within time when it is the only library that it is being installed

Also, `line_profiler` is giving an error with `pip` for Python 3.7, that's why I had shifted it to the conda installation

**Comment by rajat2004** [comment]
`msgpack` takes that long to build? This didn't happen while installing on my system.
I felt that `dlib` took the most time to build while installing `opencv`

**Comment by rajat2004** [comment]
And how did you check if `line_profiler` is giving an error with Python 3.7 @rsnk96?
There wasn't any output on the Travis log
Or did you test it on your local system

**Comment by rsnk96** [comment]
Gives an error on my local system

**Comment by rajat2004** [comment]
Yeah, `msgpack` installation is now working in Travis

**Comment by rajat2004** [comment]
But seems like `line_profiler` installation is stuck

**Comment by rajat2004** [comment]
Maybe channel needs to be specified @rsnk96?
`conda install -c conda-forge line_profiler`

[https://anaconda.org/conda-forge/line_profiler](https://anaconda.org/conda-forge/line_profiler)

**Comment by rsnk96** [comment]
Trying with the `-y` flag now

**Comment by rajat2004** [comment]
Didn't even think of that

**Comment by rsnk96** [comment]
Haha yeah, the silliest mistakes always find a way to creep up

**Comment by rajat2004** [comment]
It might have been that adding the `-y` flag was the only commit required with the original file

**Comment by rsnk96** [comment]
haha yeah. Leaving it for now though as `msgpack` still takes time on its own sweet time

**Comment by rajat2004** [comment]
Till the `-y` flag isn't merged with the repo, the Travis build will fail.
@rsnk96 Should I open a new PR to test that?

**Comment by rajat2004** [comment]
And the Travis build finished successfully!!

**Comment by rsnk96** [comment]
@rajat2004 merged now. Thanks for pointing it out, almost skipped my attention :laughing:

**Pull request merged**
