### PR TITLE
Fix Tensorflow Build

### PR DESCRIPTION
**Pull request by rajat2004**

### CODE REVIEW

**Comment by rajat2004** [comment]
Tensorflow 2 has slightly different build instructions, need to fix those before merging

**Comment by rajat2004** [comment]
Seems to be working now, problems were caused by some Bionic servers being under sync and Tensorflow docs being changed in the middle
I'm not sure about the removal of `--config=no_gcp` but since it's working...

**Comment by rajat2004** [comment]
Merging, the `nogcp` flag is anyways only for Travis

**Comment by rsnk96** [comment]
Looks good. Happy 50. This is the 50th PR :)

**Comment by rajat2004** [comment]
Didn't notice that, Yay!

**Pull request merged**
